# Generated by Django 5.2.12 on 2026-03-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='suma',
            field=models.IntegerField(default=0),
        ),
    ]
