# Generated by Django 5.2.12 on 2026-03-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_suma'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='odch',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='var',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='śr',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
