# Generated by Django 6.0.2 on 2026-03-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_odch_post_var_post_śr'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
