# Generated by Django 6.0.2 on 2026-03-17 13:48

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='email',
        ),
        migrations.RemoveField(
            model_name='post',
            name='state',
        ),
        migrations.AddField(
            model_name='post',
            name='plik1',
            field=models.FileField(default='', upload_to=blog.models.user_directory_path),
        ),
    ]
