# Generated by Django 6.0.2 on 2026-03-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_email_remove_post_state_post_plik1'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='guzik',
            field=models.BooleanField(default=False),
        ),
    ]
