# Generated by Django 6.0.2 on 2026-03-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_guzik'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='plik_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='suma',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
