# Generated by Django 5.2.12 on 2026-03-24 14:01

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(default='', max_length=20)),
                ('body', models.TextField()),
                ('suma', models.IntegerField(default=0)),
                ('plik1', models.FileField(default='', upload_to=blog.models.user_directory_path)),
            ],
        ),
    ]
