# Generated by Django 5.2.11 on 2026-03-17 13:33

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_suma_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='plik1',
            field=models.FileField(default='', upload_to=blog.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='', max_length=20),
        ),
    ]
